name: hikmah_bersama_quiz_poc
description: POC for quiz feature in Hikmah or Bersama

version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_custom_clippers: ^1.0.4
  firebase_admob: ^0.9.0+7
  admob_flutter: ^0.3.4
  flutter_dotenv: ^2.0.3
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  intro_views_flutter: ^2.8.0
  intro_slider: ^2.2.8

dev_dependencies:
  # have to use an older version of test
  test: ^1.6.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: UnicaOne
      fonts:
        - asset: assets/fonts/UnicaOne-Regular.ttf
