name: hikmah_bersama_quiz_poc
description: POC for quiz feature in Hikmah or Bersama

version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_custom_clippers: ^1.0.4
  html_unescape: ^1.0.1+3
  firebase_admob: ^0.9.0+7
  flutter_dotenv: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: UnicaOne
      fonts:
        - asset: assets/fonts/UnicaOne-Regular.ttf
